spring:
  #Application
  application:
    name: optimistic-locking-example

  #Liquibase
  liquibase:
    change-log: ${LIQUIBASE_CHANGE_LOG:classpath:db-changelog/changelog-dev.xml}


  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true

  #JPA
  datasource:
    url: jdbc:h2:mem:account-storage-db;DB_CLOSE_DELAY=-1
    username: admin
    password:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: none