spring:
  #Application
  application:
    name: optimistic-locking-example

  #Liquibase
  liquibase:
    change-log: ${LIQUIBASE_CHANGE_LOG:classpath:db-changelog/changelog-dev.xml}


  #JPA
  datasource:
    url: jdbc:postgresql://localhost:5432/account-transfer-money-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        ddl-auto: none